//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PieAnalytics.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Jobs = new HashSet<Job>();
            this.webpages_OAuthMembership = new HashSet<webpages_OAuthMembership>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual ICollection<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
    }
}
